name: MyBuild

env:
  CLANG: clang++
  GCC: g++

on:
  push:
    branches:
      - master
jobs:
  my_build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash
        working-directory: build
        
    steps:
      - uses: actions/checkout@v1
    
      - name: build-formatterlib
        run: | 
          mkdir formatterlib 
          cd formatterlib
          cmake ../../formatter_lib -DCMAKE_CXX_COMPILER=&CLANG
          cmake --build .
      
