name: MyBuild

on:
  push:
    branches:
      - master
jobs:
  build-on-linux:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash
        
    steps:
      - uses: actions/checkout@v1
      
      - name: set-compiler
        run: sudo apt install clang-11 g++
          
      - name: build-formatterlib
        run: | 
          cd formatter_lib 
          cmake . -DCMAKE_CXX_COMPILER=clang++
          cmake --build .
          cd ..

      - name: build-formatterex 
        run: |
          cd formatter_ex 
          cmake . -DCMAKE_CXX_COMPILER=clang++
          cmake --build .
          cd ..
          
      - name: build-solve
        run: |
          cd solver_app 
          cmake . -DCMAKE_CXX_COMPILER=g++
          cmake --build .
          cd ..
          
      - name: build-hello
        run: |
         cd hello_world_app 
         cmake . -DCMAKE_CXX_COMPILER=g++
         cmake --build .
         cd ..
         
  build-on-windows:
    runs-on: windows-latest
    
    defaults:
      run:
        shell: powershell
      
    steps:
      - uses: actions/checkout@v1
      
      - name: build-formatterlib
        run: | 
          cd formatter_lib
          cmake . -G "Makefiles MinGW"
          cmake --build .
          cd ..
      
