name: MyBuild

env:
  CLANG: clang++
  GCC: g++

on:
  push:
    branches:
      - master
jobs:
  my_build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash
        
    steps:
      - uses: actions/checkout@v1
    
      - name: build-formatterlib
        run: | 
          cd formatter_lib 
          cmake . -DCMAKE_CXX_COMPILER=&CLANG
          cmake --build .
          cd ..
