name: MyBuild

env:
  CLANG: clang++
  GCC: g++

on:
  push:
    branches:
      - master
jobs:
  my_build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash
        
    steps:
      - uses: actions/checkout@v1
      
      - name: set-compiler
        run: |
          sudo apt install clang-11
          
      - name: build-formatterlib
        run: | 
          cd formatter_lib 
          cmake . -DCMAKE_CXX_COMPILER=clang-11
          cmake --build .
          cd ..
